from langgraph.graph import StateGraph,START,END
from CORE.state import State
from NODES.router_node import router_node,route_next
from NODES.worker_node import worker_node
from NODES.orchestrator_node import orchestrator_node
from NODES.research_node import research_node
from NODES.fanout import fanout_to_workers
from NODES.reducer import merge_node

g=StateGraph(State)

g.add_node("router", router_node)
g.add_node("research", research_node)
g.add_node("orchestrator", orchestrator_node)
g.add_node("worker", worker_node)
g.add_node("reducer", merge_node)

g.add_edge(START, "router")
g.add_conditional_edges("router", route_next, {"research": "research", "orchestrator": "orchestrator"})
g.add_edge("research", "orchestrator")
g.add_conditional_edges("orchestrator", fanout_to_workers, ["worker"])
g.add_edge("worker", "reducer")
g.add_edge("reducer", END)

app = g.compile()

if __name__ == "__main__":
    # 1. We create a fake backpack with a topic
    test_state = {"topic": "Explain the history of CRISPR"}
    
    # 2. We pass the backpack into the compiled Graph
    print("Starting AI Graph... Please wait!")
    result = app.invoke(test_state)
    
    # 3. We print the final massive string generated by the Reducer
    print("\n=== FINAL GENERATED REPORT ===")
    print(result.get("merged_md"))